#!/bin/sh /etc/rc.common

START=98
STOP=05
USE_PROCD=1


PIDFILE=/var/run/urbackupsrv.pid
DAEMON=/usr/bin/urbackupsrv
DAEMON_CONF=/etc/urbackup/urbackupsrv.conf
DAEMON_ARGS="run --config $DAEMON_CONF --daemon --pidfile $PIDFILE"
USER="urbackup"


start_service() {

    # daemon_workdir="/usr/local/urbackupsrv/var/urbackup"
    # [ -d $daemon_workdir ] || mkdir -m 755 -p $daemon_workdir
    # chmod 0755 $daemon_workdir
    # chown -R $USER:$USER $daemon_workdir
    #
    # daemon_tmpdir="$workdir/tmp"
    # [ -d $daemon_tmpdir ] || mkdir -m 755 -p $daemon_tmpdir
    # chmod 0755 $daemon_tmpdir
    # chown -R $USER:$USER $daemon_tmpdir
    #
    # chown -R $USER:$USER /usr/local/urbackupsrv/share/urbackup

    procd_open_instance
    procd_set_param command $DAEMON
    procd_append_param command $DAEMON_ARGS
    procd_set_param user "$USER"
    procd_set_param group "$USER"
    procd_set_param pidfile $PIDFILE
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    service_stop "$DAEMON"
}
