#!/bin/sh /etc/rc.common

START=97
STOP=06
USE_PROCD=1

PIDFILE=/var/run/urbackupclient.pid
DAEMON=/usr/sbin/urbackupclientbackend
DAEMON_ARGS="-c /etc/urbackup/urbackupclient.conf -w $PIDFILE -d"

start_service() {

    procd_open_instance
    procd_set_param command $DAEMON
    procd_append_param command $DAEMON_ARGS
    procd_set_param pidfile $PIDFILE
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    service_stop "$DAEMON"
}
